### ISSUE TITLE
Automating code quality in product realisation

### ISSUE THREAD

**Issue by veit** [veit/jupyter-tutorial#30]
* [check-manifest](https://github.com/mgedmin/check-manifest)
* [mypy](http://mypy-lang.org/) for static typing
* [Black](https://github.com/python/black)
    * Config in ``pyproject.toml``:
        ```
        [tool.black]
        line-length = 79
        ```
    * Link to [Craft Your Python Like Poetry](https://treyhunner.com/2017/07/craft-your-python-like-poetry/).
* [isort](https://github.com/timothycrosley/isort)
    * Config:
        ```
        [isort]
        atomic=true
        force_grid_wrap=0
        include_trailing_comma=true
        lines_after_imports=2
        lines_between_types=1
        multi_line_output=3
        not_skip=__init__.py
        use_parentheses=true

        known_first_party=attr
        known_third_party=hypothesis,pytest,setuptools,six,zope
        ```
    * For the detection of third party packages you can use [seed-isort-config](https://github.com/asottile/seed-isort-config).
* [prettier](https://prettier.io/) for automated formatting of other file types
* [pre-commit](https://pre-commit.com/) offers a framework for running hooks before committing code.
    * Config `pre-commit-config.yaml`:
        ```
        repos:
          - repo: https://github.com/psf/black
            rev: 19.10b0
            hooks:
              - id: black
                language_version: python3.7
                # override until resolved: https://github.com/ambv/black/issues/402
            files: \.pyi?$
                types: []

          - repo: https://gitlab.com/pycqa/flake8
            rev: 3.7.9
            hooks:
              - id: flake8
                language_version: python3.7

          - repo: https://github.com/asottile/seed-isort-config
        rev: v1.9.4
            hooks:
              - id: seed-isort-config

          - repo: https://github.com/pre-commit/mirrors-isort
        rev: v4.3.21
            hooks:
              - id: isort
                additional_dependencies: [toml]
                language_version: python3.7

          - repo: https://github.com/pre-commit/pre-commit-hooks
            rev: v2.4.0
            hooks:
              - id: trailing-whitespace
              - id: end-of-file-fixer
              - id: debug-statements
        ```
    * Run `pre-commit run --all-files`
